apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date-service
  template:
    metadata:
      labels:
        app: date-service
    spec:
      containers:
        - name: data-service
          image: aguz99aa/date-service
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Europe/Rome"  # Imposta la timezone desiderata
---
apiVersion: v1
kind: Service
metadata:
  name: date-service
  #namespace: myapp-namespace
spec:
  selector:
    app: date-service
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
